### ISSUE TITLE
설치가 안되요

### ISSUE THREAD

**Issue by leesunghee1229** [daybit-exchange/pydaybit#1]
윈도우 환경에서 아나콘다 커맨드 창에서 아래와 같이 설치하면 setup.py 를 찾을수 없다고 뜨네요.

pip install -e pydaybit
Directory 'pydaybit' is not installable. File 'setup.py' not found.

혹시 어떻게 해야 해결되는지 알 수 있을까요?

**Comment by leesunghee1229** [comment]
pip install https://github.com/daybit-exchange/pydaybit/archive/master.tar.gz 
이렇게 하니까 설치 되네요...

**Comment by gyunt** [comment]
#2 와 같은 질문입니다. 

[문서](https://docs.daybit.com/#installation)와 같이 명령어를 두 줄을 입력하셔야 합니다.

```shell
$ git clone https://github.com/daybit-exchange/pydaybit
$ pip install -e pydaybit
```

**Comment by gyunt** [comment]
클론하신 폴더 안에서 설치를 시도하셨으면 다음처럼 입력하시면 됩니다.

```dos
> git clone https://github.com/daybit-exchange/pydaybit
> cd pydaybit
> pip install -e . 
```
