### ISSUE TITLE
pydaybit should either be a path to a local project or a VCS url beginning with svn+, git+, hg+, or bzr+

### ISSUE THREAD

**Issue by ehdtmdcouple** [daybit-exchange/pydaybit#2]
pip install -e pydaybit

pydaybit should either be a path to a local project or a VCS url beginning with svn+, git+, hg+, or bzr+

How can I fix?

**Comment by gyunt** [comment]
Hi, @ehdtmdcouple 

It would be two lines which already in the docs.
```shell
$ git clone https://github.com/daybit-exchange/pydaybit
$ pip install -e pydaybit
```

 In addition, I will add `pydaybit` to `pypi` ASAP.

Thanks.

**Comment by gyunt** [comment]
There is same question in Korean #1 .
