### ISSUE TITLE
websocket connection timeout error

### ISSUE THREAD

**Issue by yyespark** [daybit-exchange/pydaybit#3]
안녕하세요. 좋은 api 만들어주셔서 감사합니다.

pydaybit을 이용해 응용프로그램을 만들어보려고 하는데 기본적인 웹소켓 연결 부분에서부터 막혀서 해결을 못하고 있습니다.

phoenix/phoenix.py
async with atimeout(10, loop=self.loop):
self._socket = await websockets.connect(furl(self.url).add(self.params).url,
ssl=self._ssl,
loop=self.loop)

이 부분에서 타임아웃 에러가 납니다. 참고로 타임아웃 부분을 없애거나 타임아웃을 시간을 늘리면 거의 1-2분 후에 응답이 들어오긴 합니다.

<img width="1095" alt="screen shot 2018-11-04 at 11 56 16 pm" src="https://user-images.githubusercontent.com/19724846/48019854-4b4adf80-e0e9-11e8-9e08-71ed257742be.png">

확인 부탁드립니다.

**Comment by gyunt** [comment]
`pydaybit` 은  `websockets` 라이브러리 위에 만들어졌습니다.
websockets 의 라이브러리의 문제는 해당 프로젝트에 문의해주시기 바랍니다.

추가로 핸드쉐이크의 시간을 임의로 10초로 하였는데, 이 시간도 거래소 이용에 불편이 있는 값이니 참고하시길 바랍니다.

**Comment by gyunt** [comment]
`pydaybit` is built  on [`websockets`](https://github.com/aaugustin/websockets) library. 
The issue could be requested  on the `webscokets` project. 

Thank you.
